### ISSUE TITLE
pyuvsim error at gather step 

### ISSUE THREAD

**Issue by kbharatgehlot** [RadioAstronomySoftwareGroup/pyuvsim#279]
I used the following settings:
Ntimes = 28800
Nfreqs = 256
Nbls    = 3
Nsrc   = 1
Ntasks = 22118400

```
Traceback (most recent call last):
  File "/scratch/bgehlot/PYUVsim/run_params_pyuvsim.py", line 27, in <module>
    pyuvsim.uvsim.run_uvsim(args.paramsfile)
  File "/packages/7x/anaconda3/5.3.0/envs/pyuvsim/lib/python3.8/site-packages/pyuvsim/uvsim.py", line 467, in run_uvsim
    uv_out = run_uvdata_uvsim(input_uv, beam_list, beam_dict=beam_dict, catalog=catalog)
  File "/packages/7x/anaconda3/5.3.0/envs/pyuvsim/lib/python3.8/site-packages/pyuvsim/uvsim.py", line 421, in run_uvdata_uvsim
    full_tasklist = comm.gather(summed_local_task_list, root=0)
  File "mpi4py/MPI/Comm.pyx", line 1262, in mpi4py.MPI.Comm.gather
  File "mpi4py/MPI/msgpickle.pxi", line 680, in mpi4py.MPI.PyMPI_gather
  File "mpi4py/MPI/msgpickle.pxi", line 685, in mpi4py.MPI.PyMPI_gather
  File "mpi4py/MPI/msgpickle.pxi", line 148, in mpi4py.MPI.Pickle.allocv
  File "mpi4py/MPI/msgpickle.pxi", line 139, in mpi4py.MPI.Pickle.alloc
SystemError: Negative size passed to PyBytes_FromStringAndSize
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 3307319.0 ON cg13-2 CANCELLED AT 2020-04-01T18:05:31 ***
srun: error: cg13-17: tasks 57-59,61-67: Killed
srun: error: cg14-9: tasks 68-71: Killed
srun: error: cg13-5: tasks 37-44: Killed
srun: error: cg13-17: task 60: Killed
srun: error: cg13-15: tasks 45,47,49,51,53: Killed
srun: error: cg13-4: tasks 16-36: Killed
srun: error: cg13-2: tasks 0-15: Killed
srun: error: cg13-15: tasks 46,48,50,52,54-56: Killed
```

**Comment by aelanman** [comment]
This looks to be an internal issue with mpi4py. Mpi4py is trying to make a buffer to accept the gathered UVTask objects, but is storing the size of this buffer in an `int`. The size of a serialized UVTask object is about 452 bytes, so the number describing the size of the buffer (22118400 * 452) is overflowing.

To fix this, we'll need to figure out what the maximum task count is before this becomes an issue and split the gather into parts if it's too large.

**Comment by aelanman** [comment]
The short term solution is to split your simulation up into multiple sims with different parts of that time axis, and then add up the resulting files.
